
# PHP + NGINX Container #----------------------------------
ov-laravel5:
  restart: always
  image: tkcdocker/laravel-mongo
  container_name: ov-laravel5
  ports:
    - "80:80"
  volumes:
    - ./settings/nginx:/etc/nginx/sites-available
    - ./Code/laravel:/var/www
    - ./logs/nginx:/var/log/nginx
    - ./logs/laravel:/var/www/storage/logs
  links:
    - ov-mysql
    - ov-mysqltesting
    - ov-redis
    - ov-mongo
  privileged: true
  extra_hosts:
    - "laravel.dev:xxx.xxx.xxx.xxx"

# Mongo Container #----------------------------------------
ov-mongo:
  container_name: ov-mongo
  image: mongo
#  volumes:
#    - ./data/mongo:/data/db
#    - ./logs/mongo:/data/db

# MySQL Container #----------------------------------------
ov-mysql:
  image: laradock/mysql:latest
  container_name: ov-mysql
  ports:
    - "3309:3306"
#  volumes_from:
#    - ov-data
#  volumes:
#    - ./logs/mysql:/var/log/mysql
  environment:
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
  privileged: true


# MySQL Container #----------------------------------------
ov-mysqltesting:
#  restart: always
  image: laradock/mysql:latest
  container_name: ov-mysqltesting
  ports:
    - "3308:3306"
#  volumes_from:
#    - ov-data-test
#  volumes:
#    - ./logs/mysql-testing:/var/log/mysql
  environment:
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
  privileged: true


# Redis Container #----------------------------------------
ov-redis:
#  restart: always
  image: laradock/redis:latest
  container_name: ov-redis
  ports:
    - "6380:6379"
#  volumes_from:
#    - data
#  volumes:
#    - ./logs/redis:/var/log/redis
  restart: always
  privileged: true

# Data Volume Container #----------------------------------
ov-data:
#  restart: always
  image: laradock/data:latest
  container_name: ov-data
  volumes:
    - /var/lib/mysql
    - /var/lib/redis

# Data Volume Container #----------------------------------
ov-data-test:
  image: laradock/data:latest
  container_name: ov-data-test
  volumes:
    - /var/lib/mysql
    - /var/lib/redis


