laravel5:
  build: .
  container_name: laravel5
  ports:
    - "80:80"
    - "8081:8081"
  volumes:
    - ./settings/nginx:/etc/nginx/sites-available
    - ./logs/nginx:/var/log/nginx
    - ./Code/:/var/www
  links:
    - mongo
    - mysql
    - mysqltesting
  privileged: true #特権モード

web1:
  image: tkcdocker/laravel-mongo
  container_name: web1
  ports:
    - "8001:80"
  links:
    - mongo
    - mysql
    - mysqltesting
  privileged: true

web2:
  image: tkcdocker/laravel-mongo
  container_name: web2
  ports:
    - "8002:80"
  links:
    - mongo
    - mysql
    - mysqltesting
  privileged: true

mysql:
  image: mysql:latest
  container_name: mysql
  ports:
    - "3306:3306"
  volumes_from:
    - data-mysql
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: N
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: homestead
  privileged: true

mysqltesting:
  image: laradock/mysql:latest
  container_name: mysqltesting
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: N
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: homestead
  privileged: true

mongo:
  image: mongo:latest
  container_name: mongo
  ports:
    - "27017:27017"
  volumes_from:
    - data-mongo
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: N
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
  privileged: true

redis:
  image: laradock/redis:latest
  container_name: redis
  ports:
    - "6379:6379"
  volumes_from:
    - data-redis
  restart: always
  privileged: true

data-mysql:
  image: busybox
  container_name: data-mysql
  volumes:
    - /var/lib/mysql

data-mysql-testing:
  image: busybox
  container_name: data-mysql-testing
  volumes:
    - /var/lib/mysql

data-redis:
  image: busybox
  container_name: data-redis
  volumes:
    - /var/lib/mysql

data-mongo:
  image: busybox
  container_name: data-mongo
  volumes:
    - /data/db