ansible:
#  build: .
  image: ansible/ansible:centos6
  container_name: ansible
  ports:
    - "8091:80"
  volumes:
    - ./settings:/etc/ansible/
  links:
    - mysql
  privileged: true

mysql:
  image: mysql:latest
  container_name: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: N
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: homestead
  privileged: true

